//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaWeb.ServiceReferenceLibro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro_Ubicacion", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceBiblioteca.Modelo")]
    [System.SerializableAttribute()]
    public partial class Libro_Ubicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibreroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estante {
            get {
                return this.EstanteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstanteField, value) != true)) {
                    this.EstanteField = value;
                    this.RaisePropertyChanged("Estante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Librero {
            get {
                return this.LibreroField;
            }
            set {
                if ((object.ReferenceEquals(this.LibreroField, value) != true)) {
                    this.LibreroField = value;
                    this.RaisePropertyChanged("Librero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionField, value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaField, value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLibro.ILibro")]
    public interface ILibro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Consultar", ReplyAction="http://tempuri.org/ILibro/ConsultarResponse")]
        BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Consultar", ReplyAction="http://tempuri.org/ILibro/ConsultarResponse")]
        System.Threading.Tasks.Task<BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[]> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Consultar1", ReplyAction="http://tempuri.org/ILibro/Consultar1Response")]
        BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[] Consultar1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Consultar1", ReplyAction="http://tempuri.org/ILibro/Consultar1Response")]
        System.Threading.Tasks.Task<BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[]> Consultar1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Consultar2", ReplyAction="http://tempuri.org/ILibro/Consultar2Response")]
        BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[] Consultar2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Consultar2", ReplyAction="http://tempuri.org/ILibro/Consultar2Response")]
        System.Threading.Tasks.Task<BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[]> Consultar2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/guardaLibro", ReplyAction="http://tempuri.org/ILibro/guardaLibroResponse")]
        void guardaLibro(BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/guardaLibro", ReplyAction="http://tempuri.org/ILibro/guardaLibroResponse")]
        System.Threading.Tasks.Task guardaLibroAsync(BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion libro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibroChannel : BibliotecaWeb.ServiceReferenceLibro.ILibro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibroClient : System.ServiceModel.ClientBase<BibliotecaWeb.ServiceReferenceLibro.ILibro>, BibliotecaWeb.ServiceReferenceLibro.ILibro {
        
        public LibroClient() {
        }
        
        public LibroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[]> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[] Consultar1() {
            return base.Channel.Consultar1();
        }
        
        public System.Threading.Tasks.Task<BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[]> Consultar1Async() {
            return base.Channel.Consultar1Async();
        }
        
        public BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[] Consultar2() {
            return base.Channel.Consultar2();
        }
        
        public System.Threading.Tasks.Task<BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion[]> Consultar2Async() {
            return base.Channel.Consultar2Async();
        }
        
        public void guardaLibro(BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion libro) {
            base.Channel.guardaLibro(libro);
        }
        
        public System.Threading.Tasks.Task guardaLibroAsync(BibliotecaWeb.ServiceReferenceLibro.Libro_Ubicacion libro) {
            return base.Channel.guardaLibroAsync(libro);
        }
    }
}
