//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceBiblioteca.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public string Isbn { get; set; }
        public string Estante { get; set; }
        public string Sala { get; set; }
        public string Librero { get; set; }
        public string Posicion { get; set; }
    }
}
